language: node_js
before_install:
  - echo $PWD
  - echo $PATH
install:
  - ./run.cmd
script: 
  - export PATH=$PATH:$PWD/platform/linux_x86_64/bin
  - echo $PATH
  - cd ./server
  - npm install eslint
